name: Build Kivy APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip openjdk-17-jdk python3-pip \
          build-essential ccache libncurses5 \
          libffi-dev libssl-dev libsqlite3-dev \
          libjpeg-dev libfreetype6-dev \
          liblcms2-dev libblas-dev liblapack-dev \
          libgl1-mesa-dev libglu1-mesa-dev \
          zlib1g-dev libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-libav

        python3 -m pip install --upgrade pip
        pip install --user --upgrade buildozer cython

    - name: Build APK
      run: |
        export PATH=$HOME/.local/bin:$PATH
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app-debug-apk
        path: bin/*.apk
