name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer Cython

      - name: Fix Android SDK cmdline-tools
        run: |
          rm -rf $ANDROID_SDK_ROOT/cmdline-tools/latest || true
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          shopt -s extglob
          cp -r $ANDROID_SDK_ROOT/cmdline-tools/!('latest') $ANDROID_SDK_ROOT/cmdline-tools/latest/

      - name: Initialize Buildozer
        run: |
          buildozer init || true

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk
