name: Build Kivy APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            tar zip unzip openjdk-17-jdk python3-pip \
            build-essential ccache libffi-dev libssl-dev libsqlite3-dev \
            libjpeg-dev libfreetype6-dev liblzma-dev zlib1g-dev \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
            gstreamer1.0-libav git curl

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython
          python3 -m pip install --user python-for-android

      - name: Accept Android SDK Licenses
        run: |
          mkdir -p ~/.android
          echo "### User Agreements" > ~/.android/repositories.cfg

      - name: Initialize Buildozer
        run: |
          buildozer init || true  # если уже инициализировано — не вызывать ошибку

      - name: Build APK
        run: |
          buildozer android debug
