name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip \
          build-essential ccache libffi-dev libssl-dev \
          libsqlite3-dev libjpeg-dev libfreetype6-dev liblzma-dev \
          zlib1g-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
          gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-libav

    - name: Install buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Create virtualenv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt || true

    - name: Install Android SDK and accept licenses
      run: |
        mkdir -p $HOME/.android
        echo '### Accepting licenses' 
        yes | sdkmanager --licenses || true

        echo "Installing build-tools"
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"

    - name: Build APK
      run: |
        source venv/bin/activate
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-kivy-app
        path: bin/*.apk
